---
name: Lint files

# yamllint disable-line rule:truthy
on:
  # USE_WORKFLOW
  workflow_call:
# /USE_WORKFLOW
# USE_REPOSITORY
#  pull_request:
# /USE_REPOSITORY

jobs:
  find-changes:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: changes
        with:
          list-files: "json"
          filters: |
            json:
              - added|modified: '**/*.json'

            renovate-config:
              - added|modified:
                - 'renovate.json'
                - 'renovate.json5'
                - '.github/renovate.json'
                - '.github/renovate.json5'
                # used for shareable presets
                - 'default.json'

            dockerfile:
              - added|modified: '**/*Dockerfile*'
    outputs:
      dockerfile: ${{ steps.changes.outputs.dockerfile }}
      dockerfile_files: ${{ steps.changes.outputs.dockerfile_files }}
      json: ${{ steps.changes.outputs.json }}
      json_files: ${{ steps.changes.outputs.json_files }}
      renovate-config: ${{ steps.changes.outputs.renovate-config }}
      renovate-config_files: ${{ steps.changes.outputs.renovate-config_files }}

  lint-json:
    runs-on: ubuntu-latest
    continue-on-error: true
    if: needs.find-changes.outputs.json == 'true'
    needs: find-changes
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Run JSON Lint
        run: bash <(curl -s https://raw.githubusercontent.com/CICDToolbox/json-lint/master/pipeline.sh)

  lint-renovate:
    runs-on: ubuntu-latest
    continue-on-error: true
    if: needs.find-changes.outputs.renovate-config == 'true'
    needs: find-changes
    strategy:
      matrix:
        file: ${{ fromJson(needs.find-changes.outputs.renovate-config_files) }}
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - uses: suzuki-shunsuke/github-action-renovate-config-validator@b54483862375f51910a60c4f498e927d4f3df466 # v1.0.1
        with:
          config-path: ${{ matrix.file }}

  lint-shell:
    name: Check shell scripts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: ShellCheck
        uses: ludeeus/action-shellcheck@00cae500b08a931fb5698e11e79bfbd38e612a38 # 2.0.0

  lint-docker:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: find-changes
    if: ${{ needs.find-changes.outputs.dockerfile_files != '[]' && needs.find-changes.outputs.dockerfile_files != '' }}
    strategy:
      matrix:
        file: ${{ fromJson(needs.find-changes.outputs.dockerfile_files) }}
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@54c9adbab1582c2ef04b2016b760714a4bfde3cf # v3.1.0
        with:
          dockerfile: ${{ matrix.file }}
