---
name: "Pull Request"

# yamllint disable-line rule:truthy
on:
  # USE_WORKFLOW
  workflow_call:
# /USE_WORKFLOW
# USE_REPOSITORY
#  pull_request_target:
#    types:
#      - opened
#      - edited
#      - synchronize
#    branches-ignore:
#      - "release-please--branches--*"
# /USE_REPOSITORY

jobs:
  title:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@ad38cffc07bac6e3857755914c4c88bfd2db4da4 # v1.10.2
        id: app-token
        with:
          app-id: ${{ vars.GET_TOKEN_APP_ID }}
          private-key: ${{ secrets.GET_TOKEN_APP_PRIVATE_KEY }}
      - uses: amannn/action-semantic-pull-request@0723387faaf9b38adef4775cd42cfd5155ed6017 # v5.5.3
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        with:
          types: |
            build
            chore
            ci
            docs
            feat
            fix
            perf
            refactor
            revert
            style
            test
          # Configure which scopes are allowed.
          # deps - dependency updates
          # main - for release-please (scope used for releases)
          scopes: |
            deps
            main
          requireScope: false
          subjectPattern: ^(?![A-Z]).+$
          subjectPatternError: |
            The subject "{subject}" found in the pull request title "{title}"
            didn't match the configured pattern. Please ensure that the subject
            doesn't start with an uppercase character.
          wip: true
          validateSingleCommit: false
          validateSingleCommitMatchesPrTitle: false
