---
name: Lint files

# yamllint disable-line rule:truthy
on:
  # USE_WORKFLOW
  workflow_call:
# /USE_WORKFLOW
# USE_REPOSITORY
#  pull_request:
# /USE_REPOSITORY

jobs:
  find-changes:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: changes
        with:
          list-files: "json"
          filters: |
            json:
              - added|modified: '**/*.json'

            markdown:
              - added|modified: '**/*.md'

            renovate-config:
              - added|modified:
                - 'renovate.json'
                - 'renovate.json5'
                - '.github/renovate.json'
                - '.github/renovate.json5'
                # used for shareable presets
                - 'default.json'

            workflow:
              - added|modified:
                - '.github/workflows/*.yml'
                - '.github/workflows/*.yaml'

            dockerfile:
              - added|modified: '**/*Dockerfile*'
    outputs:
      json: ${{ steps.changes.outputs.json }}
      markdown: ${{ steps.changes.outputs.markdown }}
      renovate-config: ${{ steps.changes.outputs.renovate-config }}
      workflow: ${{ steps.changes.outputs.workflow }}
      dockerfile_files: ${{ steps.changes.outputs.dockerfile_files }}

  # FIXME
  lint-json:
    runs-on: ubuntu-latest
    continue-on-error: true
    if: needs.find-changes.outputs.json == 'true'
    needs: find-changes
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Run JSON Lint
        run: bash <(curl -s https://raw.githubusercontent.com/CICDToolbox/json-lint/master/pipeline.sh)

  # FIXME
  lint-markdown:
    runs-on: ubuntu-latest
    continue-on-error: true
    if: needs.find-changes.outputs.markdown == 'true'
    needs: find-changes
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Validate Markdown file
        run: |
          npm install -g markdownlint-cli
          markdownlint -c .config/markdownlint.yml -i CHANGELOG.md "**/*.md"

  # FIXME
  lint-renovate:
    runs-on: ubuntu-latest
    continue-on-error: true
    if: needs.find-changes.outputs.renovate-config == 'true'
    needs: find-changes
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - uses: suzuki-shunsuke/github-action-renovate-config-validator@b54483862375f51910a60c4f498e927d4f3df466 # v1.0.1

  # FIXME
  lint-shell:
    name: Check shell scripts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: ShellCheck
        uses: ludeeus/action-shellcheck@00cae500b08a931fb5698e11e79bfbd38e612a38 # 2.0.0

  # FIXME
  lint-workflow:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: find-changes
    if: needs.find-changes.outputs.workflow == 'true'
    container:
      image: rhysd/actionlint:1.7.0@sha256:5acca218639222e4afbc82fc6e9ef56cbe646ade3b07f3f5ec364b638258a244
      options: --cpus 1 --user root
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Validate Github workflows
        run: |
          mkdir .git
          actionlint -color

  lint-docker:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: find-changes
    if: ${{ needs.find-changes.outputs.dockerfile_files != '[]' && needs.find-changes.outputs.dockerfile_files != '' }}
    strategy:
      matrix:
        file: ${{ fromJson(needs.find-changes.outputs.dockerfile_files) }}
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@54c9adbab1582c2ef04b2016b760714a4bfde3cf # v3.1.0
        with:
          dockerfile: ${{ matrix.file }}

  find-changes-for-shell-output:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: changes
        with:
          list-files: "shell"
          filters: |
            yaml:
              - added|modified:
                - '**/*.yaml'
                - '**/*.yml'
    outputs:
      yaml: ${{ steps.changes.outputs.yaml }}

  lint-yaml:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: find-changes-for-shell-output
    if: needs.find-changes-for-shell-output.outputs.yaml == 'true'
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: yaml-lint
        uses: ibiqlik/action-yamllint@2576378a8e339169678f9939646ee3ee325e845c # v3.1.1
        with:
          config_file: .config/yamllint.yml
          file_or_dir: ${{ steps.filter-changes-for-shell-output.outputs.yaml_files }}
          strict: true
