---
name: Check spelling

# yamllint disable-line rule:truthy
on:
  # USE_WORKFLOW
  workflow_call:
# /USE_WORKFLOW
# USE_REPOSITORY
#  pull_request:
# /USE_REPOSITORY

jobs:
  cspell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - run: |
          # renovate: datasource=npm depName=@cspell/dict-cspell-bundle
          cspell_dict_version="2.0.68"
          npm i -D @cspell/dict-cspell-bundle@${cspell_dict_version}

          # renovate: datasource=npm depName=cspell
          cspell_version="9.8.0"
          npx cspell@${cspell_version} . -c .config/cspell.json --dot

  validate-dictionaries:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - run: .github/workflows/scripts/check_dictionaries.sh
