---
name: Close stale issues and PRs

# yamllint disable-line rule:truthy
on:
  # USE_WORKFLOW
  workflow_call:
# /USE_WORKFLOW
# USE_REPOSITORY
#  schedule:
#    - cron: "25 2 * * *"
# /USE_REPOSITORY

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@5f858e3efba33a5ca4407a664cc011ad407f2008 # v10.1.0
        with:
          # yamllint disable rule:line-length
          stale-issue-message: "This issue is stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 10 days."
          stale-pr-message: "This PR is stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 10 days."
          # yamllint enable rule:line-length
          close-issue-message: "This issue was closed because it has been stalled for 10 days with no activity."
          close-pr-message: "This PR was closed because it has been stalled for 10 days with no activity."
          exempt-issue-labels: "work-in-progress"
          exempt-pr-labels: "work-in-progress,dependency"
          days-before-stale: 30
          days-before-close: 10
          stale-issue-label: "stale"
          stale-pr-label: "stale"
