---
name: Execute ChatOps help command

# yamllint disable-line rule:truthy
on:
  # USE_WORKFLOW
  workflow_call:
# /USE_WORKFLOW
# USE_REPOSITORY
#  repository_dispatch:
#    types:
#      - help-command
# /USE_REPOSITORY

jobs:
  help-command:
    name: "ChatOps: /help"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Choose maintainer
        id: vars
        run: |
          maintainer=$(grep -oE "@[a-zA-Z0-9_-]+" .github/CODEOWNERS | shuf -n 1)
          echo "maintainer=$maintainer" >> "$GITHUB_OUTPUT"

      - name: Create comment
        uses: actions/github-script@f28e40c7f34bde8b3046d885e986cb6290c5673b # v7.1.0
        with:
          # yamllint disable rule:line-length
          script: |
            // adds a comment to the PR (there is the issue API, which works work PRs too)
            github.rest.issues.createComment({
              issue_number: context.payload.client_payload.github.payload.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Hey there ${{ steps.vars.outputs.maintainer }}, could you please help @${{ github.event.client_payload.github.payload.comment.user.login }} out?'
            })
          # yamllint enable rule:line-length
