---
name: Approve all Renovate PRs automatically

# USE_WORKFLOW
## yamllint disable-line rule:truthy
on:
  workflow_call:
    secrets:
      PAT_FOR_PR_AUTO_APPROVAL:
        required: true
# /USE_WORKFLOW
# USE_REPOSITORY
## yamllint disable-line rule:truthy
#on: pull_request_target
# /USE_REPOSITORY

jobs:
  pr-auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: github.actor == 'renovate[bot]'
    steps:
      - uses: hmarr/auto-approve-action@f0939ea97e9205ef24d872e76833fa908a770363 # v4.0.0
        with:
          review-message: "Auto approve Renovate PR (organization rule)"
          github-token: ${{ secrets.PAT_FOR_PR_AUTO_APPROVAL }}
