---
name: Lint files

# USE_WORKFLOW
## yamllint disable-line rule:truthy
on:
  workflow_call:
# /USE_WORKFLOW
# USE_REPOSITORY
## yamllint disable-line rule:truthy
#on: pull_request
# /USE_REPOSITORY

jobs:
  find-changes:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: changes
        with:
          list-files: "json"
          filters: |
            json:
              - added|modified: '**/*.json'

            renovate-config:
              - added|modified:
                - 'renovate.json'
                - 'renovate.json5'
                - '.github/renovate.json'
                - '.github/renovate.json5'
                # used for shareable presets
                - 'default.json'

            dockerfile:
              - added|modified: '**/*Dockerfile*'
    outputs:
      dockerfile: ${{ steps.changes.outputs.dockerfile }}
      dockerfile_files: ${{ steps.changes.outputs.dockerfile_files }}
      json: ${{ steps.changes.outputs.json }}
      json_files: ${{ steps.changes.outputs.json_files }}
      renovate-config: ${{ steps.changes.outputs.renovate-config }}
      renovate-config_files: ${{ steps.changes.outputs.renovate-config_files }}

  find-changes-for-shell-output:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: changes-for-shell
        with:
          list-files: "shell"
          filters: |
            markdown:
            - added|modified: '**/*.md'

            workflow:
              - added|modified:
                - '.github/workflows/*.yml'
                - '.github/workflows/*.yaml'

            yaml:
              - added|modified:
                - '**/*.yaml'
                - '**/*.yml'
    outputs:
      markdown: ${{ steps.changes-for-shell.outputs.markdown }}
      markdown_files: ${{ steps.changes-for-shell.outputs.markdown_files }}
      workflow: ${{ steps.changes-for-shell.outputs.workflow }}
      workflow_files: ${{ steps.changes-for-shell.outputs.workflow_files }}
      yaml: ${{ steps.changes-for-shell.outputs.yaml }}
      yaml_files: ${{ steps.changes-for-shell.outputs.yaml_files }}

  lint-markdown:
    runs-on: ubuntu-latest
    if: needs.find-changes-for-shell-output.outputs.markdown == 'true'
    needs: find-changes-for-shell-output
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Validate Markdown file
        run: |
          npm install -g markdownlint-cli
          # do not check CHANGELOG.md, it is generated automatically
          markdownlint -c .config/markdownlint.yml -i CHANGELOG.md ${{ needs.find-changes-for-shell-output.outputs.markdown_files }}

  lint-workflow:
    runs-on: ubuntu-latest
    needs: find-changes-for-shell-output
    if: needs.find-changes-for-shell-output.outputs.workflow == 'true'
    container:
      image: rhysd/actionlint:1.7.7@sha256:887a259a5a534f3c4f36cb02dca341673c6089431057242cdc931e9f133147e9
      options: --cpus 1 --user root
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Validate Github workflows
        run: |
          mkdir .git
          actionlint -color ${{ needs.find-changes-for-shell-output.outputs.workflow_files }}

  lint-yaml:
    runs-on: ubuntu-latest
    needs: find-changes-for-shell-output
    if: needs.find-changes-for-shell-output.outputs.yaml == 'true'
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: yaml-lint
        uses: ibiqlik/action-yamllint@2576378a8e339169678f9939646ee3ee325e845c # v3.1.1
        with:
          config_file: .config/yamllint.yml
          file_or_dir: ${{ needs.find-changes-for-shell-output.outputs.yaml_files }}
          strict: true

  lint-json:
    runs-on: ubuntu-latest
    if: needs.find-changes.outputs.json == 'true'
    needs: find-changes
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Run JSON Lint
        env:
          INCLUDE_FILES: ${{ needs.find-changes.outputs.json_files }}
        run: |
          INCLUDE_FILES=$(echo "$INCLUDE_FILES" | jq -r '. | join(",")')
          bash <(curl -s https://raw.githubusercontent.com/CICDToolbox/json-lint/master/pipeline.sh)

  lint-renovate:
    runs-on: ubuntu-latest
    if: needs.find-changes.outputs.renovate-config == 'true'
    needs: find-changes
    strategy:
      matrix:
        file: ${{ fromJson(needs.find-changes.outputs.renovate-config_files) }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: suzuki-shunsuke/github-action-renovate-config-validator@c22827f47f4f4a5364bdba19e1fe36907ef1318e # v1.1.1
        with:
          config-path: ${{ matrix.file }}

  lint-shell:
    name: Check shell scripts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: ShellCheck
        uses: ludeeus/action-shellcheck@00cae500b08a931fb5698e11e79bfbd38e612a38 # 2.0.0

  lint-docker:
    runs-on: ubuntu-latest
    needs: find-changes
    if: ${{ needs.find-changes.outputs.dockerfile_files != '[]' && needs.find-changes.outputs.dockerfile_files != '' }}
    strategy:
      matrix:
        file: ${{ fromJson(needs.find-changes.outputs.dockerfile_files) }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@54c9adbab1582c2ef04b2016b760714a4bfde3cf # v3.1.0
        with:
          dockerfile: ${{ matrix.file }}
