---
name: Prepare Release PR

# yamllint disable-line rule:truthy
on:
  # USE_WORKFLOW
  workflow_call:
    secrets:
      SEMANTIC_RELEASE_GH_TOKEN:
        required: true
# /USE_WORKFLOW
# USE_REPOSITORY
#  push:
#    branches:
#      - main
# /USE_REPOSITORY

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: googleapis/release-please-action@5c625bfb5d1ff62eadeeb3772007f7f66fdcf071 # v4.4.1
        with:
          release-type: terraform-module
          include-v-in-tag: false
          # temporary tokens do not work as they don't have access to protected tags
          token: ${{ secrets.SEMANTIC_RELEASE_GH_TOKEN }}
