---
name: Terraform

# yamllint disable-line rule:truthy
on:
  # USE_WORKFLOW
  workflow_call:
    secrets:
      TFLINT_ROLE_ARN:
        required: true
      TFLINT_AWS_REGION:
        required: true
# /USE_WORKFLOW
# USE_REPOSITORY
#  pull_request_target:
# /USE_REPOSITORY

permissions:
  id-token: write
  contents: read

jobs:
  tflint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5.1.0
        name: Cache plugin dir
        with:
          path: ~/.tflint.d/plugins
          key: tflint-${{ hashFiles('.config/tflint.hcl') }}

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@61815dcd50bd041e203e49132bacad1fd04d2708 # v5.1.1
        with:
          role-to-assume: ${{ secrets.TFLINT_ROLE_ARN }}
          role-session-name: tflint
          aws-region: ${{ secrets.TFLINT_AWS_REGION }}

      - name: install tflint
        run: |
          # renovate: datasource=github-tags depName=terraform-linters/tflint
          tflint_version="v0.64.0"

          curl -o tflint.zip -L \
            https://github.com/terraform-linters/tflint/releases/download/${tflint_version}/tflint_linux_amd64.zip
          unzip tflint.zip

      - name: Show version
        run: ./tflint --config=.config/tflint.hcl --version

      - name: Init TFLint
        run: ./tflint --config=.config/tflint.hcl --init

      - name: Run TFLint
        run: ./tflint --config=.config/tflint.hcl -f compact
