---
name: "Check spelling"

# yamllint disable-line rule:truthy
on:
  pull_request:

jobs:
  default:
    # using stable to be able to quickly switch to a working version in case the current stable is broken
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/default_spelling_callable.yml@stable
    secrets: inherit
