---
name: Try a release

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - release-dry-run

jobs:
  default:
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/default_release_dry_run_callable.yml@99c1c2f42731c6a1cd24507e3b262ea77597f053 # main
    secrets: inherit
